api:
  title: Polyglot API
  version: 1.0
  description: Translate Chinese or Russian into English
  docs_endpoints:
    openapi: /docs
    redoc: /redoc
  cors:
    origins:
      - "*"
    credentials: true
    methods:
      - "*"
    headers:
      - "*"

polyglot:
  max_batch_size: 32
  max_new_tokens: 512
  early_stopping: true
  num_beams: 5
  models:
    base_path: pretrained_models
    detection: lid.176/lid.176.ftz
    translation:
      ru-en: opus-mt-ru-en
      zh-en: opus-mt-zh-en
