api:
  title: Translator API
  version: 0.1.0
  description: Detect languages and translate input text.
  response:
    headers:
      process_duration: true
  endpoints:
    healthcheck: /_health
    docs:
      openapi: /docs
      redoc: /redoc
  no_access_log:
    - /favicon.ico
    - /_health

translator:
  max_batch_size: 32
  max_new_tokens: 512
  early_stopping: true
  num_beams: 2
  models:
    base_directory: pretrained-models
    identification: lid.176/lid.176.ftz
    translation:
      ru-en: opus-mt-ru-en
      zh-en: opus-mt-zh-en
